using System;
using System.Collections.Generic;

namespace TD.GameLoop
{
	[Serializable]
	public class GameplayTelemetrySnapshot
	{
		public int Frame;
		public float Time;
		public string GameState;
		public bool IsPaused;
		public int WaveNumber;
		public int TotalWaves;
		public bool IsSpawning;
		public int EnemiesAlive;
		public int EnemiesSpawned;
		public int TotalEnemiesInWave;
		public float WaveProgress;
		public int Currency;
		public int StartingCurrency;
		public int CurrencyGained;
		public int CurrencySpent;
		public int BaseHealth;
		public int BaseMaxHealth;
		public bool IsBaseDestroyed;
		public bool RewardOfferPending;
		public bool RewardOfferResolved;
		public string RewardOfferId;
		public string SelectedRewardId;
		public int RewardOfferCreatedForWave;
		public string SelectedReward;
		public string ActiveChallengeModifier;
		public bool CanSelectChallengeModifier;
		public float ChallengeModifierEnemyCountFactor;
		public float ChallengeModifierEnemyHealthFactor;
		public float ChallengeModifierEnemySpeedFactor;
		public float ChallengeModifierCompletionRewardFactor;
		public bool IsTowerPlacing;
		public bool IsTilePlacing;
		public int SelectedTileIndex;
		public int TileOptionCount;
		public int ActiveEnemyCount;
		public int EnemiesKilled;
		public int EnemiesLeaked;
		public string FirstActiveEnemyName;
		public string FirstActiveEnemyArchetype;
		public float FirstActiveEnemyPositionX;
		public float FirstActiveEnemyPositionY;
		public float FirstActiveEnemyPositionZ;
		public bool FirstActiveEnemyOnNavMesh;
		public bool FirstActiveEnemyHasPath;
		public bool FirstActiveEnemyPathPending;
		public string FirstActiveEnemyPathStatus;
		public float FirstActiveEnemyRemainingDistance;
		public float FirstActiveEnemyDesiredVelocityX;
		public float FirstActiveEnemyDesiredVelocityY;
		public float FirstActiveEnemyDesiredVelocityZ;
		public float FirstActiveEnemyVelocityX;
		public float FirstActiveEnemyVelocityY;
		public float FirstActiveEnemyVelocityZ;
		public float FirstActiveEnemyDistanceToBase;
		public float FirstActiveEnemyDestinationX;
		public float FirstActiveEnemyDestinationY;
		public float FirstActiveEnemyDestinationZ;
		public float BaseCenterX;
		public float BaseCenterY;
		public float BaseCenterZ;
		public int WavesCompleted;
		public int TowersUpgraded;
		public int TotalEntrances;
		public int CoveredEntrances;
		public float EntryCoverageRatio;
		public float TowerBaseConcentration;
		public bool TileMapValid;
		public bool TileMapHasBase;
		public int TileMapTileCount;
		public int TileMapOpenRoadEndCount;
		public int TileMapInvalidConnectionCount;
		public int TileMapDisconnectedTileCount;
		public int TileMapGenerationSeed;
		public List<GameplayTelemetryTile> TileMapTiles = new List<GameplayTelemetryTile>();
		public List<string> TileMapValidationErrors = new List<string>();
		public float AdaptiveEnemyHealthFactor;
		public float AdaptiveEnemyCountFactor;
		public float AdaptiveEnemySpeedFactor;
		public float AdaptiveRewardFactor;
		public float AdaptiveDifficultyScore;
		public float EnemyLevelHealthFactor;
		public float EnemyLevelCountFactor;
		public float EnemyLevelSpeedFactor;
		public float EnemyLevelDifficultyScore;
		public bool HasGeneratedWave;
		public int GeneratedWaveGroupCount;
		public float GeneratedWavePredictedDamageFraction;
		public float GeneratedWaveTensionScore;
		public int GeneratedWaveSeed;
		public List<GameplayTelemetryTower> Towers = new List<GameplayTelemetryTower>();
	}
}
